version: '3'

services:
  # navigation:
  #   image: chrisw321/db
  #   command: bash -c "npm run seed && npm run start"
  #   depends_on:
  #     - "database"
  #   ports:
  #     - "80:2999"
  database:
    container_name: database
    build: ./database
    ports:
      - "5432:5432"
