version: '3'

services:
  navigation:
    image: bcronin2/fec-airbnh-navigation
    command: bash -c "npm run seed && npm run start"
    depends_on:
      - "database"
    ports:
      - "2999:2999"
  database:
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"